configured_endpoints: 39
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/lorikeet%2Florikeet-15a8eada2bc8320411c2ab6858eafc90fbffbd6c8db5d23ce5ca4df5db2d2939.yml
openapi_spec_hash: aeba2af861b4c3be2f89a20d60aa903c
config_hash: 404f75e51e3fc69d94da11ef00f266d8
