configured_endpoints: 14
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/lorikeet%2Florikeet-1dc556faa98fbbd7ef10e6deef9112ed62cb44852c502dea5a68e9b195e4319a.yml
openapi_spec_hash: eb87b28a592ee19a0629f6ffcbf98822
config_hash: bb66f7ddce17b8bf5edbd0dcb636f22b
