configured_endpoints: 34
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/lorikeet%2Florikeet-48b61d72ca5bc1aa3009b0082d2a69f55d99f34b19e9a1b98dd24ccede094918.yml
openapi_spec_hash: 1b4c2cd3997ab2ddb7a6f5a47debddc7
config_hash: f746cc50ac24c0bf1cba53cbe8cf461a
