configured_endpoints: 14
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/lorikeet%2Florikeet-54db060cef2385998843e39b47c383f9815d80f047c2bb526ff0a191ba4ece87.yml
openapi_spec_hash: b2bfe4e24ccda9cee1dfefb3ba2016ed
config_hash: bb66f7ddce17b8bf5edbd0dcb636f22b
