configured_endpoints: 14
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/lorikeet%2Florikeet-ba88b51f75a3be764289b8f159b3fecd5ea97d9082fd6d472dd43e5cddf3a711.yml
openapi_spec_hash: ad8f1e67e23e34eee06a83315add4d25
config_hash: bb66f7ddce17b8bf5edbd0dcb636f22b
