configured_endpoints: 14
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/lorikeet%2Florikeet-90a3e656181930fe839b00e36d1aaa8e23d870dd9bf36dfcee8c5ba0bd528540.yml
openapi_spec_hash: 7e7dbfcbc8ed7f35b2d0f16c0d85b3ba
config_hash: bb66f7ddce17b8bf5edbd0dcb636f22b
