configured_endpoints: 14
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/lorikeet%2Florikeet-936fb4eccb173cbe4c9a13be381a228bc347bddb8677b042dd69ece3184e0d0f.yml
openapi_spec_hash: 12d244fd7ac5cce52fe7886bbdbb4c5d
config_hash: bb66f7ddce17b8bf5edbd0dcb636f22b
